# Generated by Django 5.2.7 on 2026-03-19 17:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Amenity name', max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class or path', max_length=100)),
                ('category', models.CharField(blank=True, help_text='Amenity category (indoor, outdoor, security, etc.)', max_length=50)),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Property title/name', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=255, unique=True)),
                ('description', models.TextField(help_text='Detailed property description')),
                ('property_type', models.CharField(choices=[('APARTMENT', 'Apartment'), ('HOUSE', 'House'), ('VILLA', 'Villa'), ('OFFICE', 'Office'), ('SHOP', 'Shop'), ('WAREHOUSE', 'Warehouse'), ('LAND', 'Land')], help_text='Type of property', max_length=20)),
                ('listing_type', models.CharField(choices=[('RENT', 'For Rent'), ('SALE', 'For Sale'), ('BOTH', 'Rent or Sale')], default='RENT', help_text='Listing type (rent/sale)', max_length=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RENTED', 'Rented'), ('SOLD', 'Sold'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('PENDING', 'Pending Approval'), ('DRAFT', 'Draft')], default='DRAFT', help_text='Current property status', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Property price or monthly rent', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', help_text='Currency code (USD, EUR, etc.)', max_length=3)),
                ('address', models.TextField(help_text='Full street address')),
                ('city', models.CharField(help_text='City name', max_length=100)),
                ('state', models.CharField(blank=True, help_text='State/Province', max_length=100)),
                ('country', models.CharField(default='USA', help_text='Country name', max_length=100)),
                ('postal_code', models.CharField(blank=True, help_text='Postal/ZIP code', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Latitude for map display', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Longitude for map display', max_digits=10, null=True)),
                ('bedrooms', models.PositiveIntegerField(default=0, help_text='Number of bedrooms', validators=[django.core.validators.MaxValueValidator(50)])),
                ('bathrooms', models.DecimalField(decimal_places=1, default=0, help_text='Number of bathrooms (allows 0.5 for half baths)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('living_area', models.DecimalField(decimal_places=2, help_text='Living area in square meters', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_area', models.DecimalField(blank=True, decimal_places=2, help_text='Total area including outdoor space', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('floors', models.PositiveIntegerField(default=1, help_text='Number of floors', validators=[django.core.validators.MaxValueValidator(200)])),
                ('year_built', models.PositiveIntegerField(blank=True, help_text='Year property was built', null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)])),
                ('garages', models.PositiveIntegerField(default=0, help_text='Number of garage spaces', validators=[django.core.validators.MaxValueValidator(20)])),
                ('featured_image', models.ImageField(blank=True, help_text='Main property image', null=True, upload_to='properties/%Y/%m/')),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured property')),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Number of times property was viewed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='Date property was published', null=True)),
                ('agent', models.ForeignKey(blank=True, help_text='Assigned agent (optional)', limit_choices_to={'role': 'AGENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_properties', to=settings.AUTH_USER_MODEL)),
                ('landlord', models.ForeignKey(help_text='Property owner (Landlord)', limit_choices_to={'role': 'LANDLORD'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(blank=True, help_text='Additional details about this amenity', max_length=255)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_amenities', to='app.amenity')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_amenities', to='app.property')),
            ],
            options={
                'verbose_name': 'Property Amenity',
                'verbose_name_plural': 'Property Amenities',
            },
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CONTRACT', 'Contract'), ('CERTIFICATE', 'Certificate'), ('FLOOR_PLAN', 'Floor Plan'), ('INSPECTION', 'Inspection Report'), ('OTHER', 'Other')], help_text='Type of document', max_length=20)),
                ('file', models.FileField(help_text='Document file', upload_to='properties/%Y/%m/documents/')),
                ('title', models.CharField(help_text='Document title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Document description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(help_text='Associated property', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.property')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Document',
                'verbose_name_plural': 'Property Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Property image', upload_to='properties/%Y/%m/gallery/')),
                ('caption', models.CharField(blank=True, help_text='Image caption/description', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(help_text='Associated property', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.property')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['slug'], name='app_propert_slug_4cdf0b_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'listing_type'], name='app_propert_status_121f05_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'property_type'], name='app_propert_city_45569b_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['-created_at'], name='app_propert_created_c795ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='propertyamenity',
            unique_together={('property', 'amenity')},
        ),
    ]
