# Generated by Django 5.2.7 on 2026-03-27 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_amenity_property_propertyamenity_propertydocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Blog post title', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the title', max_length=255, unique=True)),
                ('excerpt', models.TextField(help_text='Short excerpt or summary', max_length=500)),
                ('content', models.TextField(help_text='Full blog post content')),
                ('featured_image', models.ImageField(blank=True, help_text='Featured image for the blog post', null=True, upload_to='blog_images/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', help_text='Publication status', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Display on homepage or featured sections')),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Number of views')),
                ('read_time', models.PositiveIntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255)),
                ('published_at', models.DateTimeField(blank=True, help_text='Publication date and time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='Blog post author', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='Blog category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='app.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
