# Generated by Django 5.2.7 on 2026-04-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, help_text='Unique 4-digit user ID', max_length=4, null=True, unique=True),
        ),
    ]
