# Generated by Django 5.2.7 on 2026-04-14 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='created_by',
            field=models.ForeignKey(help_text='Agent/Admin who uploaded this property', limit_choices_to={'role__in': ['AGENT', 'SUPER_ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='landlord',
            field=models.ForeignKey(blank=True, help_text='Property owner (Landlord) - Assigned by admin/agent', limit_choices_to={'role': 'LANDLORD'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_properties', to=settings.AUTH_USER_MODEL),
        ),
    ]
