# Generated by Django 5.2.7 on 2026-04-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_property_created_by_alter_property_landlord'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Mark as primary/main image for this property'),
        ),
    ]
