# Generated by Django 5.2.7 on 2026-04-14 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_propertyimage_is_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, help_text='Unique invoice number', max_length=50, unique=True)),
                ('issue_date', models.DateField(help_text='Invoice issue date')),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Invoice amount', max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Invoice status', max_length=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid', max_digits=12)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Payment date', null=True)),
                ('description', models.TextField(blank=True, help_text='Invoice description/items')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(help_text='Tenant receiving invoice', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reference', models.CharField(editable=False, help_text='Unique payment reference', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CARD', 'Credit/Debit Card'), ('CASH', 'Cash'), ('MOBILE_MONEY', 'Mobile Money'), ('PAYSTACK', 'Paystack'), ('OTHER', 'Other')], default='PAYSTACK', help_text='Payment method', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', help_text='Payment status', max_length=20)),
                ('gateway_reference', models.CharField(blank=True, help_text='Payment gateway reference/transaction ID', max_length=255)),
                ('gateway_response', models.JSONField(blank=True, help_text='Payment gateway response data', null=True)),
                ('notes', models.TextField(blank=True, help_text='Payment notes')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When payment was processed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(help_text='Associated invoice', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='app.invoice')),
                ('tenant', models.ForeignKey(help_text='Tenant making payment', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, help_text='Unique receipt number', max_length=50, unique=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, help_text='Generated PDF receipt', null=True, upload_to='receipts/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_to', models.ForeignKey(help_text='Tenant receiving receipt', on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(help_text='Associated payment', on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='app.payment')),
            ],
            options={
                'verbose_name': 'Payment Receipt',
                'verbose_name_plural': 'Payment Receipts',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='RentalAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Rental start date')),
                ('end_date', models.DateField(help_text='Rental end date')),
                ('monthly_rent', models.DecimalField(decimal_places=2, help_text='Monthly rent amount', max_digits=12)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, help_text='Security deposit amount', max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('rent_due_day', models.PositiveIntegerField(default=1, help_text='Day of month when rent is due (1-31)')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated')], default='DRAFT', help_text='Agreement status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, help_text='Managing agent', limit_choices_to={'role': 'AGENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_agreements', to=settings.AUTH_USER_MODEL)),
                ('landlord', models.ForeignKey(help_text='Property landlord', limit_choices_to={'role': 'LANDLORD'}, on_delete=django.db.models.deletion.PROTECT, related_name='landlord_agreements', to=settings.AUTH_USER_MODEL)),
                ('rental_property', models.ForeignKey(help_text='Property being rented', on_delete=django.db.models.deletion.PROTECT, related_name='rental_agreements', to='app.property')),
                ('tenant', models.ForeignKey(help_text='Tenant renting the property', limit_choices_to={'role': 'TENANT'}, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_agreements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rental Agreement',
                'verbose_name_plural': 'Rental Agreements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='rental_agreement',
            field=models.ForeignKey(help_text='Associated rental agreement', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='app.rentalagreement'),
        ),
    ]
