# Generated by Django 5.2.7 on 2026-04-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_invoice_payment_paymentreceipt_rentalagreement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_document',
            field=models.FileField(blank=True, help_text='ID document for verification (passport, driver license, etc.)', null=True, upload_to='kyc_documents/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_verification_notes',
            field=models.TextField(blank=True, help_text='Admin notes regarding ID verification'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_verified',
            field=models.BooleanField(default=False, help_text='ID verification status - verified by admin'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_verified_at',
            field=models.DateTimeField(blank=True, help_text='Date when ID was verified', null=True),
        ),
    ]
