# Generated by Django 5.2.7 on 2026-04-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_user_id_document_user_id_verification_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_type',
            field=models.CharField(blank=True, choices=[('NATIONAL_ID', 'National ID'), ('DRIVERS_LICENSE', "Driver's License"), ('PASSPORT', 'International Passport'), ('VOTERS_CARD', "Voter's Card")], help_text='Type of ID document uploaded', max_length=20),
        ),
    ]
