# Generated by Django 5.2.7 on 2026-04-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_user_id_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_role',
            field=models.CharField(blank=True, choices=[('TENANT', 'Tenant'), ('LANDLORD', 'Landlord'), ('AGENT', 'Agent/Admin'), ('SUPER_ADMIN', 'Super Admin')], help_text='Currently active role (for role switching)', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.JSONField(blank=True, default=list, help_text='List of user roles for multi-role access'),
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.CharField(default='Nigeria', help_text='Country name', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='currency',
            field=models.CharField(default='NGN', help_text='Currency code (NGN, USD, EUR, etc.)', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TENANT', 'Tenant'), ('LANDLORD', 'Landlord'), ('AGENT', 'Agent/Admin'), ('SUPER_ADMIN', 'Super Admin')], default='TENANT', help_text='Primary user role for access control', max_length=20),
        ),
    ]
