# Generated by Django 5.2.7 on 2026-04-14 16:56

from django.db import migrations


def populate_roles_field(apps, schema_editor):
    """Populate roles field for existing users"""
    User = apps.get_model('app', 'User')
    
    for user in User.objects.all():
        # If roles is empty or None, initialize with current role
        if not user.roles:
            user.roles = [user.role]
        # Ensure current role is in roles list
        elif user.role not in user.roles:
            user.roles.append(user.role)
        
        # Set active_role if not set
        if not user.active_role:
            user.active_role = user.role
        
        # Ensure active_role is in roles list
        if user.active_role not in user.roles:
            user.active_role = user.role
        
        user.save()


def reverse_populate_roles(apps, schema_editor):
    """Reverse migration - clear roles field"""
    User = apps.get_model('app', 'User')
    User.objects.update(roles=[], active_role='')


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_user_active_role_user_roles_alter_property_country_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_roles_field, reverse_populate_roles),
    ]
