# Generated by Django 5.2.7 on 2026-04-14 17:26

from django.db import migrations


def give_all_users_dual_roles(apps, schema_editor):
    """Give all regular users both TENANT and LANDLORD roles"""
    User = apps.get_model('app', 'User')
    
    for user in User.objects.all():
        # Skip agents and super admins - they keep single role
        if user.role in ['AGENT', 'SUPER_ADMIN']:
            if not user.roles:
                user.roles = [user.role]
            elif user.role not in user.roles:
                user.roles.append(user.role)
            if not user.active_role:
                user.active_role = user.role
        else:
            # Regular users get both TENANT and LANDLORD
            user.roles = ['TENANT', 'LANDLORD']
            # Keep their original role as active
            if not user.active_role or user.active_role not in ['TENANT', 'LANDLORD']:
                user.active_role = user.role if user.role in ['TENANT', 'LANDLORD'] else 'TENANT'
        
        user.save()


def reverse_dual_roles(apps, schema_editor):
    """Reverse migration - set back to single role"""
    User = apps.get_model('app', 'User')
    User.objects.all().update(roles=[])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20260414_1756'),
    ]

    operations = [
        migrations.RunPython(give_all_users_dual_roles, reverse_dual_roles),
    ]
