# Generated by Django 5.2.7 on 2026-05-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20260414_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
    ]
