# Generated by Django 5.2.7 on 2026-06-08 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_site_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalagreement',
            name='landlord',
            field=models.ForeignKey(help_text='Property landlord', on_delete=django.db.models.deletion.PROTECT, related_name='landlord_agreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, help_text='Annual rent amount', max_digits=12, verbose_name='Yearly Rent'),
        ),
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('recipient_category', models.CharField(choices=[('ALL', 'All Users'), ('TENANTS', 'Tenants'), ('LANDLORDS', 'Landlords'), ('AGENTS', 'Agents')], default='ALL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Broadcast Message',
                'verbose_name_plural': 'Broadcast Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
